owncloud/twofactor_totp

appinfo/database.xml
appinfo/info.xml
js/settingsview.js
lib/Controller/SettingsController.php
lib/Db/TotpSecret.php
lib/Db/TotpSecretMapper.php
lib/Provider/TotpProvider.php
lib/Service/ITotp.php
lib/Service/Totp.php
tests/unit/Controller/SettingsControllerTest.php

Implementation of #27.
Verification is now mandatory to enable second-factor.
@Helios07 @DeepDiver1975 please review

make verification mandatory

---

.travis.yml
appinfo/info.xml
lib/Command/SetSecretVerificationStatusCommand.php
lib/Db/TotpSecretMapper.php
tests/phpunit.xml
tests/unit/Command/SetSecretVerificationStatusCommandTest.php
tests/unit/Db/TotpSecretMapperTest.php

resolves #46,
I thought the creation date was stored, but there is no timestamps column in the database.  @PVince81 based on your idea, I added verifysecret and unverifysecret commands without timestamp.

add commands to change verified state of secret

---

appinfo/database.xml
lib/Db/TotpSecret.php
lib/Db/TotpSecretMapper.php
lib/Service/Totp.php
tests/unit/Service/TotpTest.php

Clear PR for #61. resolves #59 .

do not allow multiple uses of the same key

---

composer.json
composer.lock
lib/Controller/SettingsController.php
tests/unit/Controller/SettingsControllerTest.php

Updating endroid/qrcode 1.6.6 deprecated to endroid/qr-code 2.5.0 (newest version available for php 5.6)
There are failures regarding this update:
```
{"reqId":"qztHBxaw9utLihGhbrWq","level":3,"time":"2018-01-12T13:35:55+00:00","remoteAddr":"85.57.168.79","user":"talion","app":"index","method":"POST","url":"\/index.php\/apps\/twofactor_totp\/settings\/enable","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method Endroid\\\\QrCode\\\\QrCode::getDataUri()\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\TwoFactor_Totp\\\\Controller\\\\SettingsController->enable(true)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#2 …
```

Updating dependency

---

.drone.yml
Makefile
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/cliTwoFactorTOTP/steps.feature
tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php
vendor-bin/behat/composer.json

Fixes #69 
I have invoked a command within the steps. I'll change that if we think that's bad. Currently, we havenot tested with multiple users as this requires webui to login and logout multiple users.

Add acceptance tests for occ

---

appinfo/app.php
appinfo/info.xml
lib/Db/TotpSecretMapper.php
lib/Hooks.php
tests/unit/Db/TotpSecretMapperTest.php
tests/unit/HooksTest.php

closes #89 
By listening `user.afterdelete` event, deleted user secrets cleaned.
I added unit tests, also tested issue scenario manually.

listen user.afterdelete event to clear deleted user secrets

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php
tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature

This adds a test for verification of two factor key on the webui. Previously, #88 tested for cli command `twofactor_totp` for verification.

Test verification of TOTP through webui

---

appinfo/routes.php
lib/Controller/TotpApiController.php
lib/Provider/TotpProvider.php
lib/Service/ITotp.php
lib/Service/Totp.php
tests/unit/Controller/TotpApiControllerTest.php
tests/unit/Provider/TotpProviderTest.php
tests/unit/Service/TotpTest.php

add OCS API for TOTP validation. Implementation of #29. @Touchwoody please test.
* **URL**
/ocs/v1.php/apps/twofactor_totp/api/v1/validate/:user_id/:key?format=json
* **Example test query for curl **
``
curl -u admin:pass 'http://base_url/ocs/v1.php/apps/twofactor_totp/api/v1/validate/{user_id}/{key}?format=json'
``
* **Method:**
`GET`
*  **URL Params**
**Required:**
`user_id=[string]`
`key=[string]`
```
* **Success Response:**
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"result":true}}}
* **Fail Response:**
{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"result":false}}}
* **User or Secret Not Found Response:**
{"ocs":{"meta":{"status":"failure","statuscode":404,"message" …
```

add validate api for totp

---

Makefile

This repo has a `Makefile` that includes everything in the dist tarball except for specifically-excluded things. That is the reverse logic to most of the other `make dist` scripts.
So we have to exclude all the new CI infrastructure files added in recent times.

exclude other new CI files from tarball

---

appinfo/info.xml
composer.json
composer.lock
vendor-bin/behat/composer.json

because the app is now being tested only against core `stable10` upcoming `10.2` that has dropped PHP 5.6 support.

Adjust composer files for 'drop PHP 5.6'

---

.drone.yml

I noticed that https://drone.owncloud.com/owncloud/twofactor_totp/202/80 failed last night but there was nothing reported in the build channel.
Add the missing `notify` step to drone.

Add notify step to drone

---

tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php

Issue #117 
webUI acceptance test scenario `webUITwoFactorTOTP/keyVerification.feature:11` fails intermittently.
https://drone.owncloud.com/owncloud/twofactor_totp/210/112
The DOM element that has the "Verified" text can exist but not yet be visible. We need to wait until it is visible before trying to get the text.
Also fix a couple of minor typos in method names.

Wait till verify msg is visible

---

composer.lock

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
- Updating symfony/options-resolver (v2.8.49 => v2.8.50): Loading from cache
- Updating symfony/polyfill-ctype (v1.10.0 => v1.11.0): Loading from cache
- Updating symfony/property-access (v2.8.49 => v2.8.50): Loading from cache
Writing lock file
Generating autoload files
```

Bump symfony components

---

.drone.yml

This test guarantee that the ```twofactor_totp``` app runs correctly against 10.2.1 tarball.
Core 10.2.1 is officially released, we need ```twofactor_totp``` app to run correctly against this latest release.

twofactor_totp app test against 10.2.1 tarball

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiTwoFactorTOTP/steps.feature
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php

The result of last verification request made using OTP can be checked via API.
#38

Test for two factor authentication

---

appinfo/info.xml
lib/Command/DeleteRedundantSecretsCommand.php
lib/Db/TotpSecretMapper.php
tests/unit/Command/DeleteRedundantSecretsCommandTest.php
tests/unit/Db/TotpSecretMapperTest.php

Resolves #110
This PR adds a command for deleting non-existing users secret.

Add command for deleting redundant secrets

---

.drone.starlark
.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/lib/VerificationPage.php
tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature
tests/acceptance/features/webUIapiTwoFactorTOTP/keyVerificationByAPI.feature
tests/acceptance/features/webUIcliTwoFactorTOTP/keyVerificationByCLI.feature

Notes: 
1) the previous `drone.yml` ran `webUITwoFactorTOTP` and `cliTwoFactorTOTP` acceptance test suites, but did not seem to run the `apiTwoFactorTOTP` acceptance test suite. That has been fixed here.
2) there were no tests with Oracle. When I tried to run PHP unit tests with Oracle, there were problems. See issue #140 
3) The `api` and `cli` acceptance test suites actually need to do webUI actions in their scenario setup `Given` steps. They really need to run `make test-acceptance-webui`. So I have renamed the suites so that they start with `webUI`. That makes all the processing by starlark, `Makefile` and... work in the "standard" way. (Previously the suites looked like API and CLI suites but has `@webUI` tag in the feature files, which was tricky and did not work nicely with the …

Initial drone starlark

---

.drone.starlark
.drone.yml

`phpunit` tests are already running successfully with PHP 7.3
Add acceptance test runs with PHP 7.3  + core `10.3.0` to check that PHP 7.3 is fine.

Run TOTP acceptance tests on PHP 7.3

---

composer.lock

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): Loading from cache
Writing lock file
Generating autoload files
```
dependabot has not found this. Maybe it is not running on this repo.

Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0)

---

.drone.starlark
tests/unit/Db/TotpSecretMapperTest.php
vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`

Coding standard 2.0.0

---

appinfo/info.xml
composer.json
composer.lock
lib/Controller/SettingsController.php
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/unit/Controller/SettingsControllerTest.php

The rebased version of https://github.com/owncloud/twofactor_totp/pull/113
closes #105 
As discussed in #105, we wanted to migrate to a small QR code library to reduce tarball size. Therefore this PR changes endroid/qr-code with bacon/bacon-qr-code which is used by endroid for generating QR codes.

remove endroid/qrcode dependency to reduce package size

---

.drone.star
.gitignore
appinfo/info.xml

For some reason this app has a max PHP version specified. Increase it from 7.3 to 7.4.
An app release will be needed so people can use this with the upcoming core 10.5.0 on PHP 7.4

Support PHP 7.4

---

lib/Service/Totp.php
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php
tests/acceptance/features/lib/VerificationPage.php

Fixes #170 
When the key starts with '0', typecasting to int operation loses that leading '0'. This problem has been fixed by removing the cast operation.
This situation discovered with random CI failures and we have added some retry scenarios. Since these scenarios no longer needed, the related commit has been reverted.

Fix casting problem

---

composer.json
composer.lock
lib/Service/Totp.php
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/unit/Service/TotpTest.php

`christian-riesen/otp` v2 has been out for a while. The major version release https://github.com/ChristianRiesen/otp/releases/tag/2.0.0 back in 2016 does not seem to have any real BC breaks, just a change to the supported PHP versions.
Fixes https://github.com/owncloud/twofactor_totp/issues/22

Update christian-riesen/otp to 2.6

---

.drone.star

Fixes #213 
The encryption app now only supports oC10.7 or later.

[tests-only] Do not run pipelines with encryption against old oC10

---

tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php
tests/acceptance/features/lib/VerificationPage.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

templates/challenge.php
tests/acceptance/features/lib/VerificationPage.php

... to match with the core login layout.
Related: https://github.com/owncloud/twofactor_totp/issues/237
Before:
After:

Align the code input field with the submit button on login

---

phpunit.xml

This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198

[tests-only][full-ci]Tidy up the phpunit xml file `twofactor_totp` app

---

.drone.star
tests/acceptance/features/webUITOTPGuests/guests.feature

https://github.com/owncloud/core/pull/40442 changed the email server used in tests from mailhog to inbucket. It also changed the tag used in feature files from `@mailhog` to `@email`
So make the same change here.
Issue https://github.com/owncloud/QA/issues/771

[tests-only] [full-ci] Change mailhog tag to email

---

.drone.star
lib/Db/TotpSecretMapper.php
lib/Service/Totp.php
vendor-bin/phan/composer.json

`phan` will report errors if any of the code is not compatible with PHP 7.3.
This app still supports PHP 7.3 when used with oC10 core 10.11 and earlier.

[tests-only] [full-ci] Run phan with php 7.3

---

.drone.star

Part of: https://github.com/owncloud/encryption/issues/393

[full-ci] remove php occ encryption:select-encryption-type from drone

---

lib/Command/DeleteRedundantSecretsCommand.php
lib/Command/SetSecretVerificationStatusCommand.php

Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
Preparation for https://github.com/owncloud/core/issues/39630

Always return an int from Symfony Command execute method

---

lib/Controller/SettingsController.php
lib/Provider/TotpProvider.php
lib/Service/OtpGen.php
lib/Service/Totp.php
templates/challenge.php
tests/unit/Controller/SettingsControllerTest.php
tests/unit/Provider/TotpProviderTest.php
tests/unit/Service/OtpGenTest.php

Related https://github.com/owncloud/enterprise/issues/5219

Show qr on challenge page if not configured for the user

---

lib/Provider/TotpProvider.php
lib/Service/ITotp.php
lib/Service/Totp.php

Ref: https://github.com/owncloud/enterprise/issues/6139
The problem was caused by an unexpected redirection which caused a second secret to be generated and stored, and it was different than the one shown in the QR.
The PR will only create new secrets if the user doesn't have one, otherwise it will show the same QR (if it hasn't been verified)

Fix problem with enforced 2fa and encryption

---

appinfo/info.xml
lib/Command/DeleteSecret.php
lib/Db/TotpSecretMapper.php
tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
tests/acceptance/features/webUIcliTwoFactorTOTP/deleteSecret.feature
tests/unit/Command/DeleteSecretTest.php
tests/unit/Db/TotpSecretMapperTest.php

This allows admins to reset the secret in order to allow the user to login in case the user has lost the phone and he's locked out of his account.
Rel: https://github.com/owncloud/enterprise/issues/6252

feat: allow occ admin to delete user's secrets
