owncloud/twofactor_totp

lib/Controller/SettingsController.php, tests/phpunit.xml, tests/unit/Controller/SettingsControllerTest.php
fixes https://github.com/owncloud/twofactor_totp/issues/7
=> Add missing commits 0.4.2

appinfo/routes.php, js/settingsview.js, lib/Controller/SettingsController.php
follow up of https://github.com/owncloud/twofactor_totp/pull/5
=> Karakayasemi oc10 ready

Makefile
Little change to have makefiles more consistent.
=> Moved from appstore to dist

lib/Provider/TotpProvider.php
=> Changed title in 2FA login

.travis.yml, appinfo/info.xml
=> add PHP7.2 to tests

README.md
remove scrutinizer badge from readme and update travis badge
=> remove scrutinizer badge from readme

.php_cs.dist, Makefile, composer.json, composer.lock, tests/unit/phpunit.xml, vendor-bin/owncloud-codestyle/composer.json, vendor-bin/owncloud-codestyle/composer.lock
Add `make test-php-style` and `make test-php-unit` commands in makefile
=> Add style check and Unit test to makefile

.drone.yml, Makefile
Move tests CI from travis to drone
fixes  #52
=> Move CI from travis to drone

CHANGELOG.md, Makefile, appinfo/info.xml
Closes https://github.com/owncloud/twofactor_totp/issues/84
=> Release 0.5.2

Makefile, phpcs.xml, vendor-bin/php_codesniffer/composer.json
1) Implement php_codesniffer like in other repos with acceptance tests
2) Standardize the ``vendor-bin/behat`` like done in other repos
=> php_codesniffer and tidy vendor-bin-behat changes

tests/acceptance/features/cliTwoFactorTOTP/steps.feature
PR #90 has been merged, so this scenario is expected to pass now.
Ref: comment https://github.com/owncloud/twofactor_totp/pull/90#issuecomment-458148523
=> Unskip acceptance test scenario for issue 89

Makefile
Part of issue https://github.com/owncloud/QA/issues/609
=> Remove unneeded composer.phar references in Makefile

tests/acceptance/features/cliTwoFactorTOTP/steps.feature
fixes #99 and changes usernames to more standard ones
=> remove unneeded test steps

CHANGELOG.md, Makefile, appinfo/info.xml
Closes https://github.com/owncloud/twofactor_totp/issues/95
=> Release 0.5.3

lib/Controller/SettingsController.php, phpunit.xml, tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php, tests/unit/Controller/TotpApiControllerTest.php, tests/unit/HooksTest.php, tests/unit/Provider/TotpProviderTest.php, tests/unit/Service/TotpTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) phpunit enable failOnRisky failOnWarning 
3) remove unused use statements
=> Phpunit 5 6

tests/acceptance/features/cliTwoFactorTOTP/steps.feature, tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature
that changed in core https://github.com/owncloud/core/pull/35438
=> Adjust create user steps

tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php, tests/acceptance/features/lib/VerificationPage.php, tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature
Includes tests to check the workflow of this app
https://github.com/owncloud/twofactor_totp/issues/94
=> two factor authentication workflow

.drone.yml
Currently we only run app tests against stable10 to make sure they will be compatible with the future OC core platform release.
This test guarantee that the ```twofactor_totp``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611
=> twofactor_totp app test against latest tarball

CHANGELOG.md, appinfo/info.xml
=> Release 0.6.0

tests/acceptance/features/apiTwoFactorTOTP/steps.feature
PR https://github.com/owncloud/twofactor_totp/pull/131 adds api tests for OCS api v1. This PR adds api test for ocs v2.
Fixed: https://github.com/owncloud/twofactor_totp/issues/132
CI
=> Implement api tests for OCS v2 

.drone.yml, appinfo/info.xml
Issue https://github.com/owncloud/enterprise/issues/3187
=> Add unit tests on PHP 7.3

CHANGELOG.md, appinfo/info.xml
=> Bump version number and update changelog

Makefile
to be more like other app repos.
Issue #147 
Note: different app repos do this `make dist` stuff in various different ways. Is the way that I have chosen the "current" standard, or some old way?
=> Refactor Makefile dist

.drone.starlark, .drone.yml
do not only test 10.3.0 but the latest published release, so it will test any next release automatically
=> test latest tarball

CHANGELOG.md, Makefile
=> Merge back Release 0.6.1 branch

.drone.starlark, .drone.yml
This PR adds config for running acceptance tests with encryption enabled.
Resolves #93
=> Run with encryption enabled

.drone.starlark, .drone.yml, phpunit.xml, tests/unit/Command/DeleteRedundantSecretsCommandTest.php, tests/unit/Command/SetSecretVerificationStatusCommandTest.php, tests/unit/Controller/SettingsControllerTest.php, tests/unit/Controller/TotpApiControllerTest.php, tests/unit/Db/TotpSecretMapperTest.php, tests/unit/HooksTest.php, tests/unit/Provider/TotpProviderTest.php, tests/unit/Service/TotpTest.php, vendor-bin/behat/composer.json
Similar to https://github.com/owncloud/configreport/pull/121
=> Adjust tests

composer.lock
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
- Updating symfony/options-resolver (v2.8.50 => v2.8.52): Loading from cache
- Updating symfony/polyfill-ctype (v1.12.0 => v1.14.0): Loading from cache
- Updating symfony/property-access (v2.8.50 => v2.8.52): Loading from cache
Writing lock file
Generating autoload files
```
=> symfony updates

.drone.star, lib/Provider/TotpProvider.php, lib/Service/Totp.php, phpstan.neon, vendor-bin/phpstan/composer.json
Related - owncloud/QA#642
Update phpstan to 0.12
=> [Tests-Only] Update phpstan to latest version

tests/unit/Command/DeleteRedundantSecretsCommandTest.php, tests/unit/Command/SetSecretVerificationStatusCommandTest.php, vendor-bin/behat/composer.json
Part of https://github.com/owncloud/QA/issues/647
=> Implement phpunit v8

tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php, tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php, tests/acceptance/features/lib/VerificationPage.php
This PR is incomplete and tries to resolve the failing acceptance tests in nightly.
Investigation for issue #170
=> [Tests-Only] Retry totp key if it is invalid

tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php, tests/acceptance/features/lib/PersonalSecuritySettingsPageWithTOTPEnabled.php, tests/acceptance/features/lib/VerificationPage.php
=> [Tests-Only] Revert changes in totp

CHANGELOG.md, appinfo/info.xml
Closes https://github.com/owncloud/twofactor_totp/issues/180
=> Merge back Release 0.7.0

.drone.star
https://github.com/doctrine/dbal/pull/4106 released and doctrine/dbal has been updated on core. Oracle tests should pass now.
Fixes #140
=> add oracle to test matrix databases

composer.lock
https://github.com/khanamiryan/php-qrcode-detector-decoder/releases/tag/1.0.4
fixes #198
=> Update khanamiryan/qrcode-detector-decoder (1.0.3 => 1.0.4)

README.md
=> Update README.md -> Added Authy

CHANGELOG.md, appinfo/info.xml
=> Release 0.7.1

tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature, tests/acceptance/features/webUIapiTwoFactorTOTP/keyVerificationByAPI.feature, tests/acceptance/features/webUIcliTwoFactorTOTP/keyVerificationByCLI.feature
like was done in core last week.
Fixes CI
=> [tests-only] Specify skeleton in tests

CHANGELOG.md, appinfo/info.xml
Merge back to master
Closes #217 
Closes #223
=> Release 0.7.2

tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
core PR https://github.com/owncloud/core/pull/39036 changed the parameters of various test helper functions. Adjust the calls.
=> [tests-only] [full-ci] Adjust calls to test helper functions

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.7.3

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.7.4

tests/acceptance/features/webUITOTPGuests/guests.feature, tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature, tests/acceptance/features/webUIapiTwoFactorTOTP/keyVerificationByAPI.feature, tests/acceptance/features/webUIcliTwoFactorTOTP/keyVerificationByCLI.feature
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:
=> [full-ci] [tests-only] Refactored inter scenarios space

l10n/.tx/config
similar to https://github.com/owncloud/activity/pull/1162 and many other PRs done in the oC10 app repos in recent days.
=> fix: fix config file for new transifex client

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> merge back Release 0.7.5

.drone.star, composer.json, composer.lock, lib/Command/DeleteRedundantSecretsCommand.php, lib/Command/SetSecretVerificationStatusCommand.php, lib/Controller/SettingsController.php, lib/Controller/TotpApiController.php, lib/Db/TotpSecret.php, lib/Hooks.php, lib/Provider/TotpProvider.php, lib/Service/ITotp.php, lib/Service/Totp.php, lib/Settings/PersonalPanel.php, tests/unit/Controller/TotpApiControllerTest.php, tests/unit/HooksTest.php, tests/unit/Provider/TotpProviderTest.php, tests/unit/Service/TotpTest.php, vendor-bin/behat/composer.json, vendor-bin/owncloud-codestyle/composer.json, vendor-bin/php_codesniffer/composer.json, vendor-bin/phpstan/composer.json
- update `.drone.star` to latest from activity app
- update code-style to v4
- update other dependencies
```
- Upgrading dasprid/enum (1.0.3 => 1.0.4): Extracting archive
- Upgrading khanamiryan/qrcode-detector-decoder (1.0.5.2 => 1.0.6): Extracting archive
```
=> CI changes and dependency bumps

.drone.star
Part of: https://github.com/owncloud/QA/issues/818
=> [tests-only][full-ci] update ci

l10n/ca.js, l10n/ca.json, l10n/de.js, l10n/de.json, l10n/de_DE.js, l10n/de_DE.json, l10n/es_MX.js, l10n/es_MX.json, l10n/oc.js, l10n/oc.json, l10n/ro.js, l10n/ro.json, l10n/uk.js, l10n/uk.json
=> [tx] updates from transifex

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> merge back Release 0.8.1

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.9.0
